### PR TITLE
Tidy Plugin - Comments & Colours

### PR DESCRIPTION
**Pull request by RobLoweMOJ**

### CODE REVIEW

**Review by brown-a2 — APPROVED** [review]
Looks good to me, see what others think though - anything to add/remove.

**Comment by RobLoweMOJ** [comment]
Thanks for feedback @brown-a2 . Im going to remove the video block (as its blank) and renumber the blocks. In a separate pr. As i thought that would be too much in one PR.

**Comment by brown-a2** [comment]
cool, sounds good

**Comment by brown-a2** [comment]
...do we even need the numbers?

**Pull request merged**
